---
- name: restart Filebeat
  become: true
  service:
    name: filebeat
    state: restarted
    enabled: true
  when: (ansible_virtualization_type != 'docker') and
        (ansible_virtualization_type != 'kvm')